### ISSUE TITLE
[New Upstream Version] New Stable QDirStat Release: V1.9

### ISSUE THREAD

**Issue by shundhammer** [jlesage/docker-qdirstat#11]
### Idea

Dear maintainers of QDirStat in all those distros out there,
there is a brand new stable release of QDirStat: V1.9

  https://github.com/shundhammer/qdirstat/releases/tag/1.9

Release highlights:

- Greatly improved the visual appearance of the treemap 

- Dominant (very large) items are now highlighted in bold font in the 
  tree view

- New "Find" function in the scanned directory tree

- Added support for bookmarks

- New documentation to explain the treemap

- Some small improvements

- Bug fixes

**Comment by jlesage** [comment]
Thanks, I'm currently working on this!

**Comment by jlesage** [comment]
New image available.
