### ISSUE TITLE
New stable QDirStat release: V1.7.1

### ISSUE THREAD

**Issue by shundhammer** [jlesage/docker-qdirstat#3]
https://github.com/shundhammer/qdirstat/releases/tag/1.7.1

# Release Highlights

- New "Discover" actions to easily find
   - the largest files
   - the newest files
   - the oldest files
    - files with multiple hard links
    - broken symbolic links
    - sparse files

![QDirStat-discover](https://user-images.githubusercontent.com/11538225/113592209-26018900-9635-11eb-84c8-762e2ab9f631.png)

- Now showing the target of symbolic links in the details panel
- Menu reorganization
- Bug fixes

**Comment by jlesage** [comment]
New image available, thanks!
