### ISSUE TITLE
New stable QDirStat Release: V1.8

### ISSUE THREAD

**Issue by shundhammer** [jlesage/docker-qdirstat#5]
https://github.com/shundhammer/qdirstat/releases/tag/1.8

# Release Highlights

- New view: _File Age Statistics_

  ![](https://raw.githubusercontent.com/shundhammer/qdirstat/master/screenshots/QDirStat-file-age-years.png)

  ![](https://raw.githubusercontent.com/shundhammer/qdirstat/master/screenshots/QDirStat-file-age-months.png)

  This shows the number of files per year and/or per month that were last modified in that year or month, together with the total size of those files and a percent bar for both (number and total size).

- Navigation history like in a web browser (_Back_, _Forward_)

- Bug fixes

- Some small improvements

**Comment by jlesage** [comment]
Thanks, new image is now available!
