### ISSUE TITLE
Please Add QDirStat Version Number

### ISSUE THREAD

**Issue by shundhammer** [jlesage/docker-qdirstat#6]
Please add the version number of QDirStat to the download page so users see what they will get.

See also https://github.com/linuxserver/docker-qdirstat/issues/2 for the background of this.

**Comment by jlesage** [comment]
What do you mean by download page ?

Version is indicated in release notes (https://github.com/jlesage/docker-qdirstat/releases).

**Comment by shundhammer** [comment]
Ah, okay, I had overlooked that one. That should do well enough. Sorry for the noise. ;-)

**Comment by jlesage** [comment]
No problem!
